"
I am a notebook model
"
Class {
	#name : 'ManifestVespucciNotebookElementExtractor',
	#superclass : 'PackageManifest',
	#category : 'VespucciNotebookElementExtractor-Manifest',
	#package : 'VespucciNotebookElementExtractor',
	#tag : 'Manifest'
}

{ #category : 'asserting' }
ManifestVespucciNotebookElementExtractor class >> shouldBeIncludedByDefaultInMetamodelsWith: aCollectionOfPackages [
	^ true
]
